# Default values for mysql-chart.
replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: "8.0"

# MySQL 환경 변수 설정
env:
  - name: MYSQL_ROOT_PASSWORD
    value: "mysql-root-password"
  - name: MYSQL_DATABASE
    value: "myapp"
  - name: MYSQL_USER
    value: "myuser"
  - name: MYSQL_PASSWORD
    value: "mypassword"

# ServiceAccount 설정 (필수!)
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# 서비스 설정
service:
  type: NodePort
  port: 3306
  targetPort: 3306
  nodePort: 30306

# 기본 설정들
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

# MySQL 볼륨 설정 (선택사항)
persistence:
  enabled: true
  storageClass: "local-path"
  accessMode: ReadWriteOnce
  size: 8Gi