# Default values for mysql-chart.
replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: "8.0"

# MySQL 환경 변수 설정
env:
  - name: MYSQL_ROOT_PASSWORD
    value: "mysql-root-password"
  - name: MYSQL_DATABASE
    value: "myapp"
  - name: MYSQL_USER
    value: "myuser"
  - name: MYSQL_PASSWORD
    value: "mypassword"

# ServiceAccount 설정
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# 서비스 설정
service:
  type: NodePort
  port: 3306
  targetPort: 3306
  nodePort: 30306

# Ingress 설정
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: mysql.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# 기본 설정들
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 999

securityContext:
  runAsUser: 999
  runAsGroup: 999
  runAsNonRoot: true

resources:
  limits:
    memory: "1Gi"
    cpu: "500m"
  requests:
    memory: "512Mi"
    cpu: "250m"

# 라이브니스 및 레디니스 프로브
livenessProbe:
  exec:
    command:
      - sh
      - -c
      - "mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD"
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - "mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD"
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 5
  failureThreshold: 3

# Auto Scaling 설정
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# 볼륨 설정
volumes: []
volumeMounts: []

# 노드 선택 및 할당
nodeSelector: {}
tolerations: []
affinity: {}

# 네트워크 정책
networkPolicy:
  enabled: false

# MySQL 볼륨 설정
persistence:
  enabled: true
  storageClass: "local-path"
  accessMode: ReadWriteOnce
  size: 8Gi