
# Default values for mysql-chart.
replicaCount: 1

image:
  repository: mysql  # nginx → mysql로 변경
  pullPolicy: IfNotPresent
  tag: "8.0"  # MySQL 8.0 버전

# MySQL 환경 변수 설정
env:
  - name: MYSQL_ROOT_PASSWORD
    value: "mysql-root-password"
  - name: MYSQL_DATABASE
    value: "myapp"
  - name: MYSQL_USER
    value: "myuser"
  - name: MYSQL_PASSWORD
    value: "mypassword"

service:
  type: NodePort
  port: 3306
  targetPort: 3306
  nodePort: 30306