apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mysql
    targetRevision: 9.23.0
    helm:
      values: |
        auth:
          rootPassword: mysql-root-password
          database: myapp
          username: myuser
          password: mypassword
        
        primary:
          service:
            type: NodePort
            nodePorts:
              mysql: 30306
        
          persistence:
            enabled: true
            storageClass: "local-path"
            size: 8Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: mysql

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true