apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-aws-ec2-cluster-role
rules:
  - apiGroups: ["aws.upbound.io"]
    resources:
      - providerconfigs
      - providerconfigs/status
      - providerconfigusages          # ✅ 이것 추가
      - providerconfigusages/status   # ✅ 이것도 추가
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-aws-ec2-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-aws-ec2-cluster-role
subjects:
  - kind: ServiceAccount
    name: provider-aws-ec2-b120731a8699
    namespace: crossplane-system