apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provider-aws-ec2-cluster-role
rules:
  - apiGroups: ["aws.upbound.io"]
    resources: ["providerconfigs", "providerconfigs/status"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-aws-ec2-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-aws-ec2-cluster-role
subjects:
  - kind: ServiceAccount
    name: provider-aws-ec2-b120731a8699  # ← 정확한 이름으로 수정
    namespace: crossplane-system