apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=ghcr.io/kmkhm/my-java-image
    argocd-image-updater.argoproj.io/myapp.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myapp.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/myapp.update-strategy: latest
    argocd-image-updater.argoproj.io/myapp.pull-secret: pullsecret:argocd/ghcr-secret

#    notifications.argoproj.io/subscribe.on-deployed.slack: deployment
#    notifications.argoproj.io/subscribe.on-sync-failed.slack: deployment



spec:
  project: default
  source:
    repoURL: https://github.com/KMKHM/infra-test
    path: helm/backend/backend-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true